# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161202_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='settings.MEDIA_ROOT/avatars/default-avatar.png', null=True, upload_to='avatars/%Y/%m/%d'),
        ),
    ]
