# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
